import { AlertCircle, RefreshCw, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Alert, AlertDescription } from "@/components/ui/alert";

interface EmptyStateProps {
  onRefresh?: () => void;
  isLoading?: boolean;
}

export function EmptyState({ onRefresh, isLoading }: EmptyStateProps) {
  return (
    <div className="flex flex-col items-center justify-center min-h-[400px] space-y-6 p-8 text-center">
      <div className="flex flex-col items-center space-y-4">
        <div className="p-4 rounded-full bg-muted">
          <FileText className="h-8 w-8 text-muted-foreground" />
        </div>
        
        <div className="space-y-2">
          <h3 className="text-xl font-semibold">No Documents Available</h3>
          <p className="text-muted-foreground max-w-md">
            Legal documents are generated by automated data sync from documents.gov.lk. 
            The next sync will happen when GitHub Actions run.
          </p>
        </div>
      </div>
      
      <Alert className="max-w-md">
        <AlertCircle className="h-4 w-4" />
        <AlertDescription>
          Data is synchronized every 2 hours via GitHub Actions. 
          If you just deployed this app, please wait for the first sync to complete.
        </AlertDescription>
      </Alert>
      
      {onRefresh && (
        <Button 
          onClick={onRefresh} 
          disabled={isLoading}
          variant="outline"
          className="gap-2"
        >
          <RefreshCw className={`h-4 w-4 ${isLoading ? 'animate-spin' : ''}`} />
          Check for Data
        </Button>
      )}
      
      <div className="text-sm text-muted-foreground">
        <p>Expected data sources:</p>
        <ul className="mt-2 space-y-1 text-xs">
          <li>• Acts and Bills from documents.gov.lk</li>
          <li>• Government Gazettes</li>
          <li>• Legal Forms and Notices</li>
          <li>• Enhanced documents from Hugging Face datasets</li>
        </ul>
      </div>
    </div>
  );
}