name: Sync Legal Data (documents.gov.lk)

on:
  schedule:
    - cron: "0 0 * * *"   # Once daily at midnight UTC
  workflow_dispatch:        # Allow manual triggers

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        job:
          - { name: "gazettes", cmd: "gazettes --from-year 2004 --to-year 2025 --out public/data/gazettes", out: "public/data/gazettes" }
          - { name: "extra-gazettes", cmd: "extra-gazettes --from-year 2004 --to-year 2025 --out public/data/extra-gazettes", out: "public/data/extra-gazettes" }
          - { name: "acts", cmd: "acts --out public/data/acts", out: "public/data/acts" }
          - { name: "bills", cmd: "bills --out public/data/bills", out: "public/data/bills" }
          - { name: "forms", cmd: "forms --out public/data/forms", out: "public/data/forms" }
          - { name: "notices", cmd: "notices --out public/data/notices", out: "public/data/notices" }
          - { name: "hf-acts-full", cmd: "hf-acts-full --out public/data/hf-acts-full", out: "public/data/hf-acts-full" }
          - { name: "hf-acts-chunks", cmd: "hf-acts-chunks --out public/data/hf-acts-chunks", out: "public/data/hf-acts-chunks" }
          - { name: "github-acts", cmd: "github-acts --out public/data/github-acts", out: "public/data/github-acts" }
          - { name: "github-extraordinary-gazettes", cmd: "github-extraordinary-gazettes --out public/data/github-extraordinary-gazettes", out: "public/data/github-extraordinary-gazettes" }
          - { name: "github-bills", cmd: "github-bills --out public/data/github-bills", out: "public/data/github-bills" }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install system dependencies and Rust
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libxslt-dev python3-dev build-essential
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source ~/.cargo/env
          rustc --version
          cargo --version
      - name: Install deps
        run: |
          source ~/.cargo/env
          python -m pip install --upgrade pip setuptools wheel
          pip install -r scrapers/requirements.txt
          # Install datasets package for Hugging Face integration
          pip install datasets>=2.14.0
      - name: Run ${{ matrix.job.cmd }}
        run: python -m scrapers.cli ${{ matrix.job.cmd }}
      - name: Upload data artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-${{ matrix.job.name }}
          path: ${{ matrix.job.out }}
          if-no-files-found: warn

  merge:
    runs-on: ubuntu-latest
    needs: scrape
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Download all data artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: docs-*
          merge-multiple: true
          path: .
      - name: Merge latest feeds
        run: python -m scrapers.cli merge-latest --root public/data
      - name: Commit changes (if any)
        run: |
          git config user.name  "gh-actions"
          git config user.email "actions@users.noreply.github.com"
          git add public/data || true
          if ! git diff --cached --quiet; then
            git commit -m "Sync: merged latest @ $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes."
          fi